#!/usr/bin/env ansible-playbook
# Alpine: ./playbook.yaml      Chrome OS: sudo ./playbook.yaml
---
- name: Create groups to run different plays on different distributions
  hosts: all
  tags: always
  tasks:
    - name: Group by distribution
      group_by: { key: "{{ ansible_distribution }}" }

- name: Install binaries on Chrome OS
  hosts: Chrome-OS
  become: true
  gather_facts: no
  tasks:
    - name: ar
      get_url:
        url: https://busybox.net/downloads/binaries/1.27.1-i686/busybox_AR
        dest: /usr/local/bin/ar
        mode: 0755
    - name: busybox.static
      unarchive:
        creates: /usr/local/bin/busybox.static
        mode: 0755
        dest: /usr/local/
        remote_src: yes
        src: "{{ mirror }}v3.7/main/x86_64/busybox-static-1.27.2-r6.apk"
        extra_opts: bin/busybox.static
    - name: unshare (link to busybox.static)
      file:
        path: /usr/local/bin/unshare
        src: /usr/local/bin/busybox.static
        state: link
    - name: jq
      get_url:
        url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
        dest: /usr/local/bin/jq
        mode: 0755

- name: Setup command line shell on Chrome OS
  hosts: Chrome-OS
  become: true
  gather_facts: false
  tasks:
    - name: Folder for shell profile settings
      file: path=/usr/local/etc/profile.d/ state=directory mode=0755
    - name: Copy OSC52 functions into profile
      copy:
        src: "{{ playbook_dir }}/chroot/etc/profile.d/osc52.sh"
        dest: /usr/local/etc/profile.d/
    - name: Write settings to ~/.bashrc
      lineinfile:
        path: /home/chronos/user/.bashrc
        line: "{{ item }}"
      with_items:
        - set -o vi
        - 'alias ac="sh {{ playbook_dir }}/enter.sh"'
        - "for i in /usr/local/etc/profile.d/*.sh ; do \
           if [ -r $i ] ; then . $i; fi ; done"
        - export EDITOR="/usr/bin/vim"
