---
- git:
    # Difficult to use as an optional package
    repo: https://github.com/pearofducks/ansible-vim
    dest: /usr/share/vim/vimfiles/pack/vim-ansible/start/ansible-vim
- file:
    path: /usr/share/vim/vimfiles/after/indent/
    state: directory
    mode: 0755
- name: Simple indenting
  copy:
    dest: /usr/share/vim/vimfiles/after/indent/ansible.vim
    content: set autoindent& cindent& smartindent& indentexpr&
- lineinfile:
    line: https://nl.alpinelinux.org/alpine/edge/testing
    path: /etc/apk/repositories
- name: install ansible-lint
  apk:
    # py3-ansible-lint depends on ansible which fails under py3
    name: py2-ansible-lint py2-packaging
    update_cache: yes
