---
- name: ar
  get_url:
    url: https://busybox.net/downloads/binaries/1.27.1-i686/busybox_AR
    dest: /usr/local/bin/ar
    mode: 0755
- name: busybox.static
  unarchive:
    creates: /usr/local/bin/busybox.static
    mode: 0755
    dest: /usr/local/
    remote_src: yes
    src: "{{ mirror }}v3.7/main/x86_64/busybox-static-1.27.2-r6.apk"
    extra_opts: bin/busybox.static
- name: unshare (link to busybox.static)
  file:
    path: /usr/local/bin/unshare
    src: /usr/local/bin/busybox.static
    state: link
- name: jq
  get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    dest: /usr/local/bin/jq
    mode: 0755
- name: runc
  get_url:
    url: "https://github.com/opencontainers/runc/releases/download/v1.0.0-rc4/\
      runc.amd64"
    dest: /usr/local/bin/runc
    mode: 0755
    checksum: "sha256:\
      742318df7f36aba6135fe5f3ee378d75ec8bf6974f2238eee527b1f8e46d0112"
- name: umoci
  get_url:
    url: "https://github.com/openSUSE/umoci/releases/download/v0.3.1/\
      umoci.amd64"
    dest: /usr/local/bin/umoci
    mode: 0755
    checksum: "sha256:\
      68a4d5864d936bf6e3826dc0147c45f081d1c0b047cbb30f97d13df7d890dc5d"
