---
- name: Checkout vim-markdownfmt
  git:
    repo: https://github.com/moorereason/vim-markdownfmt
    dest: /usr/share/vim/vimfiles/pack/markdown/opt/vim-markdownfmt
    version: b3c3dec8f3cf6ebbac07b0ba53e3c9ac78dff794
- name: Test for compiled binary
  stat:
   path: "{{ markdownfmt_binary }}"
  register: binary
- name: Install binary if missing
  block:
    - name: Make Alpine 3.7 Community repository available to install go
      lineinfile:
        path: /etc/apk/repositories
        line: "@community {{ mirror }}v3.7/community"
    - name: Install libc
      apk: name=libc-dev
      register: libc
    - name: Install go
      apk: name=go@community
      register: go
    - name: Install markdownfmt with `go get`
      command: go get -u github.com/shurcooL/markdownfmt
      environment: { GOPATH: /tmp/go, GOBIN: /usr/local/bin }
      args:
        creates: "{{ markdownfmt_binary }}"
  when: not (binary.stat.isreg is defined and binary.stat.isreg)
- name: Clean up
  block:
  - name: Clean up after `go get`
    file: path=/tmp/go state=absent
  - name: Remove libc if added
    apk: name=libc-dev state=absent
    when: libc.changed
  - name: Remove go if added
    apk: name=go state=absent
    when: go.changed
- name: vim ftplugin directory for settings
  file: path=/usr/share/vim/vimfiles/ftplugin/ state=directory mode=0755
- name: Custom vim settings in ftplugin
  copy:
    dest: /usr/share/vim/vimfiles/ftplugin/markdown.vim
    content: |
      setlocal spell tabstop=3 shiftwidth=3
      packadd vim-markdownfmt
      augroup markdownfmt
        autocmd!
        autocmd BufWritePre <buffer> call markdownfmt#Format()
      augroup END
- name: Directory for disabling spell checking of modelines
  file: state=directory path=/usr/share/vim/vimfiles/after/syntax mode=0755
- name: Disable spell checking of HTML coments for modelines
  copy:
    content: >
      syn region htmlCommentPart contained start=+--+ end=+--\s*+
      contains=@htmlPreProc,@NoSpell
    dest: /usr/share/vim/vimfiles/after/syntax/markdown.vim
